### ISSUE TITLE
Can't compile due to "error: reached the type-length limit"

### ISSUE THREAD

**Issue by xiaochuanyu** [hello-rust/lychee#6] opened 2020-10-07 02:59 UTC
```
❯ cargo build
   Compiling lychee v0.3.0 (/Users/xiaochuanyu/stuff/lychee)
error: reached the type-length limit while instantiating `<std::vec::IntoIter<std::future:...]>>, ()}]>, ()}]>}]>>::Future}]>`
    --> /Users/xiaochuanyu/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:2015:5
     |
2015 | /     fn fold<B, F>(mut self, init: B, mut f: F) -> B
2016 | |     where
2017 | |         Self: Sized,
2018 | |         F: FnMut(B, Self::Item) -> B,
...    |
2024 | |         accum
2025 | |     }
     | |_____^
     |
     = note: consider adding a `#![type_length_limit="2332107"]` attribute to your crate
```
I tried doing whats suggested but got similar error again with higher suggested limit.
Eventually adding `#![type_length_limit="7912782"]` to top of `main.rs` worked.

**Comment by mre** [comment] 2020-10-07 16:28
I can reproduce it on my machine. There seems to be a bug in the async/futures stack somewhere that blows up those types. 🤔 It seems to be a recursion problem during code generation.

**Comment by mre** [comment] 2020-10-07 16:28
Looks like it's a recent issue with the mail checking crate: https://github.com/amaurymartiny/check-if-email-exists/issues/568

**Comment by xiaochuanyu** [comment] 2020-10-14 23:09
@mre fyi I tried downgrading `check-if-email-exists` but ran into compile errors due its dependencies.
I found a workaround instead, see #9.

**Comment by mre** [comment] 2020-10-14 23:57
Nice! Thanks for that @xiaochuanyu.
Really weird. Given that this unblocks the other PR and that it's a good idea to use the latest toolchain anyway I'm very happy to merge this.

**Comment by mre** [comment] 2020-10-15 00:11
@pawroman found this ticket: https://github.com/rust-lang/rust/issues/54540. I'll mention it in the `check-if-email-exists` thread from above.
Guess we can close this. 👏

**Closed by mre** 2020-10-15 00:11 UTC
Labels: bug

**Comment by untitaker** [comment] 2020-10-24 10:11
Was this issue really fixed or just worked around for in CI? Lychee still can't be compiled locally on osx.

**Comment by mre** [comment] 2020-10-24 12:39
Are you on Rust 1.47?

**Comment by untitaker** [comment] 2020-10-24 13:21
I was not, sorry for the noise.

**Comment by mre** [comment] 2020-10-24 20:38
No worries. Thanks for trying lychee. We'd be interested to hear about your experience. You could comment here or open issues if you find any. :smiley:
